"""add approved phase1 tables

Revision ID: 363a56874e2e
Revises: 0001_phase1
Create Date: 2026-07-14 13:47:34.337192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '363a56874e2e'
down_revision: Union[str, None] = '0001_phase1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_identity',
    sa.Column('face_identity_id', sa.UUID(), nullable=False),
    sa.Column('identity_lookup_hmac', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('external_identity_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('face_identity_id'),
    sa.UniqueConstraint('identity_lookup_hmac')
    )
    op.create_table('inference_profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('detector_model', sa.String(length=128), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_inference_profile_active', 'inference_profile', ['active'], unique=False)
    op.create_table('process_record',
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('process_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')"),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_index('ix_process_record_status_started', 'process_record', ['status', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_process_record_type_started', 'process_record', ['process_type', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('process_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('status_before', sa.String(length=16), nullable=True),
    sa.Column('status_after', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status_after IS NULL OR status_after IN ('pending','running','completed','failed')"),
    sa.CheckConstraint("status_before IS NULL OR status_before IN ('pending','running','completed','failed')"),
    sa.ForeignKeyConstraint(['process_id'], ['process_record.process_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_process_event_process_sequence', 'process_event', ['process_id', 'sequence'], unique=False)
    op.add_column('person', sa.Column('face_identity_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'person', 'face_identity', ['face_identity_id'], ['face_identity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'face_identity_id')
    op.drop_index('ix_process_event_process_sequence', table_name='process_event')
    op.drop_table('process_event')
    op.drop_index('ix_process_record_type_started', table_name='process_record')
    op.drop_index('ix_process_record_status_started', table_name='process_record')
    op.drop_table('process_record')
    op.drop_index('ix_inference_profile_active', table_name='inference_profile')
    op.drop_table('inference_profile')
    op.drop_table('face_identity')
    # ### end Alembic commands ###
